CC=C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
CCFLAGS=

.PHONY: all clean pack install 

all: CalculatorIVS.exe 

CalculatorIVS.exe: 
	$(CC) CalculatorIVS/CalculatorIVS.sln

clean: 
	del *.cache *.exe
